#include "std_include.hpp"
#include "game_settings.hpp"

#include "main_module.hpp"
#include "components/common/toml_ext.hpp"

namespace components
{
	std::string get_current_game_version_string() {
		return std::string(std::to_string(COMP_MOD_VERSION_MAJOR) + "." + std::to_string(COMP_MOD_VERSION_MINOR) + "." + std::to_string(COMP_MOD_VERSION_PATCH));
	}

	void game_settings::write_game_settings_toml()
	{
		const std::string file_path = glob::root_path + "\\l4d2-rtx\\game_settings.toml";
		std::filesystem::create_directories(std::filesystem::path(file_path).parent_path());

		std::ofstream file;
		file.open(file_path.c_str());

		file << "# This file is autogenerated. Valid modifications of settings are considered and will be written back to the file.\n";
		file << "# Installing a new version of the compatibility mod might restore settings whose defaults have changed.\n\n";

		const std::uint32_t setting_count = sizeof(var_definitions) / sizeof(variable);
		for (auto s = 0u; s < setting_count; s++)
		{
			auto var = reinterpret_cast<variable*>(reinterpret_cast<char*>(&vars) + s * sizeof(variable));

			const auto desc_lines = utils::split(std::string(var->m_desc), '\n');
			for (const auto& line : desc_lines) {
				file << "# " + line << std::endl;
			}

			file << "# Type: " << var->get_str_type() << " || Default: " << var->get_str_value(true) << std::endl;
			file << "# Ver: " << var->get_ver_string() << std::endl;
			file << var->m_name << " = " << var->get_str_value() << std::endl << std::endl;
		}

		file.close();
	}

	/// Func used to parse and set game settings
	/// @return						true if parsed successfully or if defaults were written if no file found, false if parsing failed
	bool game_settings::parse_toml()
	{
		// helper
		auto to_vec = [](const toml::value& entry, const var_type type, float* default_vec = nullptr)
			{
				std::vector<float> result;
				const size_t size_for_vec = type == var_type_vec2 ? 2u : type == var_type_vec3 ? 3u : type == var_type_vec4 ? 4u : 0u;

				if (entry.is_array())
				{
					if (entry.as_array().size() == size_for_vec)
					{
						for (const auto& val : entry.as_array())
						{
							if (val.is_floating())
							{
								result.push_back((float)val.as_floating());
								continue;
							}
							TOML_ERROR("[GameSettings] #to_vec", val, "expected float but got value_t of => %d ", val.type());
						}
						return result;
					}
					TOML_ERROR("[GameSettings] #to_vec", entry, "unexpected array size of => %d ", entry.as_array().size());
				}
				TOML_ERROR("[GameSettings] #to_vec", entry, "expected a vector but got value_t => %d ", entry.type());

				switch (type)
				{
				default:
					result = { 0, 0, 0, 0 };
					break;
				case var_type_vec2:
					result = { default_vec[0], default_vec[1] };
					break;
				case var_type_vec3:
					result = { default_vec[0], default_vec[1], default_vec[2] };
					break;
				case var_type_vec4:
					result = { default_vec[0], default_vec[1], default_vec[2], default_vec[3] };
					break;
				}

				return result;
			};

		if (std::filesystem::exists("l4d2-rtx\\game_settings.toml"))
		{
			try
			{
				auto config = toml::parse("l4d2-rtx\\game_settings.toml");
				const auto current_comp_version = utils::version_t::from_string(get_current_game_version_string());

				//vars.decal_dirt_shader_contrast.set_config_name()
				// ---------------------------------------
				// Used to assign toml settings
				// - check setting version, only read val if setting on disk is older than version the setting was last changed on - use the default val otherwise
				// - guard against invalid version
				// - save users game_settings value which is later used to write to the file if the user hits save

#define ASSIGN(name)																															\
					if (config.contains((#name)))																												\
					{																																			\
						std::string setting_last_comment = config.at(#name).comments().back();																	\
						if (setting_last_comment.starts_with("# Ver: "))																						\
						{																																		\
							setting_last_comment.erase(0, 7); const auto s_version = utils::version_t::from_string(setting_last_comment);				\
							if (vars.##name.m_version <= s_version && s_version <= current_comp_version)														\
							{																																	\
								switch (vars.##name.get_type())																									\
								{																																\
								case (var_type_boolean):																										\
										vars.##name.set_var(common::toml_ext::to_bool(config.at(#name), vars.##name.get_as<bool>()), true); break;		\
								case (var_type_integer):																										\
										vars.##name.set_var(common::toml_ext::to_int(config.at(#name), vars.##name.get_as<int>()), true); break;		\
								case (var_type_value):																											\
										vars.##name.set_var(common::toml_ext::to_float(config.at(#name), vars.##name.get_as<float>()), true); break;	\
								case (var_type_vec2):																											\
								case (var_type_vec3):																											\
								case (var_type_vec4):																											\
										const auto vec = to_vec(config.at(#name), vars.##name.get_type(), vars.##name.get_as<float*>());						\
										vars.##name.set_vec(vec.data(), true); break;																			\
								}																																\
								vars.##name.set_dirty(false); vars.##name.set_base_user_from_current(); \
							} else { utils::log("GameSettings", std::format("Not using saved value for {} because default setting was updated in a recent update.", vars.##name.m_name), utils::LOG_TYPE::LOG_TYPE_WARN); } \
						} \
					}

				ASSIGN(lod_forcing);
				ASSIGN(force_graphic_settings);
				ASSIGN(enable_3d_sky);
				ASSIGN(default_nocull_distance);

				ASSIGN(flashlight_offset_player);
				ASSIGN(flashlight_offset_bot);
				ASSIGN(flashlight_intensity);
				ASSIGN(flashlight_volumetric_scale);
				ASSIGN(flashlight_radius);
				ASSIGN(flashlight_angle);
				ASSIGN(flashlight_softness);
				ASSIGN(flashlight_expo);

				ASSIGN(flashlight_inner_intensity);
				ASSIGN(flashlight_inner_volumetric_scale);
				ASSIGN(flashlight_inner_radius);
				ASSIGN(flashlight_inner_angle);
				ASSIGN(flashlight_inner_softness);
				ASSIGN(flashlight_inner_expo);

				ASSIGN(debug_info_distance);
				ASSIGN(player_backwards_offset);

			#undef ASSIGN
			}

			catch (const toml::syntax_error& err)
			{
				utils::log("GameSettings", err.what(), utils::LOG_TYPE::LOG_TYPE_ERROR, true);
				utils::log("GameSettings", "Not writing defaults! Please check 'game_settings.toml' or remove the file to re-generate it on next startup!", utils::LOG_TYPE::LOG_TYPE_STATUS, true);
				return false;
			}
		}

		// always re-write file
		write_game_settings_toml();
		return true;
	}

	ConCommand xo_gamesettings_update {};
	void game_settings::xo_gamesettings_update_fn()
	{
		game_settings::parse_toml();
		main_module::cross_handle_map_and_game_settings();
	}

	game_settings::game_settings()
	{
		parse_toml();

		// ----
		game::con_add_command(&xo_gamesettings_update, "xo_gamesettings_update", xo_gamesettings_update_fn, "Reloads the game_settings.toml file");

		m_initialized = true;
		log("GameSettings", "Module initialized.", utils::LOG_TYPE::LOG_TYPE_DEFAULT, false);
	}
}