rtx.skyBrightness = 4.0
rtx.bloom.burnIntensity = 2.0

rtx.volumetrics.enableFogRemap = True
rtx.volumetrics.depthOffset = 0.05
rtx.volumetrics.froxelDepthSliceDistributionExponent = 2
rtx.volumetrics.froxelMaxDistanceMeters = 100
rtx.volumetrics.transmittanceColor = 0.999, 0.999, 0.999
rtx.volumetrics.singleScatteringAlbedo = 0.999, 0.999, 0.999
rtx.volumetrics.fogRemapMaxDistanceMinMeters = 1
rtx.volumetrics.fogRemapMaxDistanceMaxMeters = 40
rtx.volumetrics.fogRemapTransmittanceMeasurementDistanceMinMeters = 20
rtx.volumetrics.fogRemapTransmittanceMeasurementDistanceMaxMeters = 100
rtx.volumetrics.fogRemapColorMultiscatteringScale = 0.1