rtx.skyBrightness = 1.500
rtx.bloom.burnIntensity = 1.0
rtx.volumetrics.enableFogRemap = True
rtx.volumetrics.singleScatteringAlbedo = 0.94, 0.92, 0.79
rtx.volumetrics.fogRemapColorMultiscatteringScale = 0.15
rtx.volumetrics.froxelMaxDistanceMeters = 100
rtx.viewDistance.distanceMode = 2
rtx.viewDistance.distanceFadeMin = 3500
rtx.viewDistance.distanceFadeMax = 7600
rtx.viewDistance.noiseScale = 8