rtx.skyBrightness = 0.5
rtx.volumetrics.enableFogRemap = True
rtx.volumetrics.enableFogColorRemap = False
rtx.volumetrics.froxelDepthSliceDistributionExponent = 2.25
rtx.volumetrics.singleScatteringAlbedo = 0.94, 0.92, 0.79
rtx.volumetrics.froxelMaxDistanceMeters = 100
rtx.volumetrics.fogRemapColorMultiscatteringScale = 0.1
rtx.volumetrics.enableAtmosphere = True
rtx.volumetrics.atmospherePlanetRadiusMeters = 2000
rtx.volumetrics.atmosphereHeightMeters = 1
rtx.viewDistance.distanceMode = 2
rtx.viewDistance.distanceFadeMin = 2500
rtx.viewDistance.distanceFadeMax = 4000
rtx.viewDistance.noiseScale = 12
