rtx.skyBrightness = 4.00
rtx.bloom.burnIntensity = 1.0
rtx.volumetrics.enableFogRemap = True
rtx.volumetrics.enableFogColorRemap = False
rtx.volumetrics.singleScatteringAlbedo = 0.5, 0.5, 0.5
rtx.volumetrics.fogRemapMaxDistanceMinMeters = 1500
rtx.volumetrics.fogRemapMaxDistanceMaxMeters = 2000
rtx.volumetrics.fogRemapTransmittanceMeasurementDistanceMinMeters = 5000
rtx.volumetrics.fogRemapTransmittanceMeasurementDistanceMaxMeters = 10000
rtx.volumetrics.fogRemapColorMultiscatteringScale = 0.20
rtx.volumetrics.enableAtmosphere = True
rtx.volumetrics.atmospherePlanetRadiusMeters = 2000
rtx.volumetrics.atmosphereHeightMeters = 20
rtx.dust.enable = True
rtx.dust.numberOfParticles = 100000