rtx.skyBrightness = 2.5
rtx.volumetrics.enableFogRemap = True
rtx.volumetrics.froxelDepthSliceDistributionExponent = 2
rtx.volumetrics.froxelMaxDistanceMeters = 100
rtx.volumetrics.singleScatteringAlbedo = 0.999, 0.999, 0.999
rtx.volumetrics.enableAtmosphere = True
rtx.volumetrics.atmospherePlanetRadiusMeters = 200
rtx.volumetrics.atmosphereHeightMeters = 25
rtx.volumetrics.fogRemapColorMultiscatteringScale = 0.15