rtx.skyBrightness = 1.000
rtx.bloom.burnIntensity = 2.0
rtx.froxelDepthSliceDistributionExponent = 0.52
rtx.froxelMaxDistance = 2500
rtx.volumetricSingleScatteringAlbedo = 0.94, 0.94, 0.94
rtx.fogRemapMaxDistanceMin = 1500
rtx.fogRemapMaxDistanceMax = 2000
rtx.fogRemapTransmittanceMeasurementDistanceMin = 5000
rtx.fogRemapTransmittanceMeasurementDistanceMax = 10000
rtx.fogRemapColorMultiscatteringScale = 0.39
rtx.viewDistance.distanceMode = 2
rtx.viewDistance.distanceFadeMin = 3500
rtx.viewDistance.distanceFadeMax = 4500
rtx.viewDistance.noiseScale = 8